module.exports = {
  projects: [
    {
      displayName: 'Expo Module',
      preset: 'expo-module-scripts',
      testEnvironment: 'node',
      transformIgnorePatterns: [
        'node_modules/(?!(expo-module-scripts|jest-expo|@react-native|react-native|react-clone-referenced-element|@expo|@voltrajs)/)',
      ],
      moduleNameMapper: {
        '^@voltrajs/android$': '<rootDir>/../android/src/index.ts',
        '^@voltrajs/android/client$': '<rootDir>/../android/src/client.ts',
        '^@voltrajs/android/server$': '<rootDir>/../android/src/server.ts',
        '^@voltrajs/android-server$': '<rootDir>/../android-server/src/index.ts',
        '^@voltrajs/core$': '<rootDir>/../core/src/index.ts',
        '^@voltrajs-example/(.*)$': '<rootDir>/../../example/$1',
        '^@voltrajs/ios$': '<rootDir>/../ios/src/index.ts',
        '^@voltrajs/ios/client$': '<rootDir>/../ios/src/client.ts',
        '^@voltrajs/ios/server$': '<rootDir>/../ios/src/server.ts',
        '^@voltrajs/ios-server$': '<rootDir>/../ios-server/src/index.ts',
        '^@voltrajs/server$': '<rootDir>/../server/src/index.ts',
      },
      testMatch: ['<rootDir>/src/**/*.expo.test.ts?(x)'],
    },
    {
      displayName: 'Node.js',
      preset: 'react-native',
      testEnvironment: 'node',
      transformIgnorePatterns: [
        'node_modules/(?!(jest-expo|@react-native|react-native|react-clone-referenced-element|@expo|@voltrajs)/)',
      ],
      testMatch: ['<rootDir>/src/**/*.node.test.ts?(x)'],
      moduleNameMapper: {
        '^@voltrajs/android$': '<rootDir>/../android/src/index.ts',
        '^@voltrajs/android/client$': '<rootDir>/../android/src/client.ts',
        '^@voltrajs/android/server$': '<rootDir>/../android/src/server.ts',
        '^@voltrajs/android-server$': '<rootDir>/../android-server/src/index.ts',
        '^@voltrajs/core$': '<rootDir>/../core/src/index.ts',
        '^@voltrajs-example/(.*)$': '<rootDir>/../../example/$1',
        '^@voltrajs/ios$': '<rootDir>/../ios/src/index.ts',
        '^@voltrajs/ios/client$': '<rootDir>/../ios/src/client.ts',
        '^@voltrajs/ios/server$': '<rootDir>/../ios/src/server.ts',
        '^@voltrajs/ios-server$': '<rootDir>/../ios-server/src/index.ts',
        '^@voltrajs/server$': '<rootDir>/../server/src/index.ts',
        voltra: '<rootDir>/src/server.ts',
        '^(\\.{1,2}/.*)\\.js$': '$1',
      },
    },
  ],
}
