import { ConfigPlugin, withPodfile as withExpoPodfile } from '@expo/config-plugins'

const BEGIN_MARKER = '# @voltra-widget-target BEGIN'
const END_MARKER = '# @voltra-widget-target END'

// Matches a legacy (pre-marker) block emitted by older plugin versions: a bare header comment
// followed directly by the `target '<name>' do ... end` block, with no surrounding markers.
// Non-greedy up to the first line-start `end` — our generated block never nests another
// `do...end`, so this always lands on the block's own closing `end`.
const LEGACY_BLOCK_RE =
  /\n?# Voltra Widget Extension Target\n# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN\ntarget '[^']*' do\n[\s\S]*?\nend/

// Matches a marked block (any target name) end-to-end, inclusive of both markers.
const MARKED_BLOCK_RE = new RegExp(`${BEGIN_MARKER}[\\s\\S]*?${END_MARKER}`)

/**
 * Generates the Podfile target content for the widget extension (unwrapped, no markers).
 */
function getTargetContent(targetName: string): string {
  return `# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  require 'pathname'
  project_root = "#{Pod::Config.instance.installation_root}/.."
  voltra_client_root = \`node --print "require.resolve('@use-voltra/ios-client/package.json', {paths: ['#{project_root}']})" 2>/dev/null\`.strip.gsub('/package.json', '')
  raise "Voltra: could not resolve @use-voltra/ios-client from #{project_root}. Is @use-voltra/ios-client installed, and is node on PATH for pod install?" if voltra_client_root.empty?
  voltra_widget_podspec_root = File.join(voltra_client_root, 'ios')
  voltra_widget_podspec_root = File.realpath(voltra_widget_podspec_root) if File.exist?(voltra_widget_podspec_root)
  podspec_dir_path = Pathname.new(voltra_widget_podspec_root).relative_path_from(Pathname.new(__dir__)).to_path

  pod 'VoltraWidget', :path => podspec_dir_path
end`
}

function buildMarkedBlock(targetName: string): string {
  return `${BEGIN_MARKER}\n${getTargetContent(targetName)}\n${END_MARKER}`
}

/**
 * Idempotently inserts/upgrades the Voltra widget target block in Podfile contents:
 * - marked block already present → replaced in place (covers renamed targets too, since the
 *   markers are name-agnostic)
 * - legacy (pre-marker) block present → replaced with the new marked block
 * - neither present → appended
 */
export function upsertWidgetTarget(contents: string, targetName: string): string {
  const markedBlock = buildMarkedBlock(targetName)

  if (MARKED_BLOCK_RE.test(contents)) {
    return contents.replace(MARKED_BLOCK_RE, markedBlock)
  }

  if (LEGACY_BLOCK_RE.test(contents)) {
    return contents.replace(LEGACY_BLOCK_RE, `\n${markedBlock}`)
  }

  return `${contents.trimEnd()}\n\n${markedBlock}\n`
}

export interface ConfigurePodfileProps {
  targetName: string
}

/**
 * Plugin step that adds (or upgrades) the Podfile target for the widget extension.
 */
export const configurePodfile: ConfigPlugin<ConfigurePodfileProps> = (config, { targetName }) => {
  return withExpoPodfile(config, (podfile) => {
    podfile.modResults.contents = upsertWidgetTarget(podfile.modResults.contents, targetName)
    return podfile
  })
}

export const __test__ = { BEGIN_MARKER, END_MARKER, getTargetContent }
