import { __test__, upsertWidgetTarget } from './podfile'

const { BEGIN_MARKER, END_MARKER } = __test__

const TARGET_NAME = 'VoltraWidgetExtension'

const BASE_PODFILE = `platform :ios, '15.1'

target 'MyApp' do
  use_expo_modules!

  target 'MyAppTests' do
    inherit! :complete
  end
end
`

/** Reconstructs the pre-hardening (v2.1.0) unmarked block verbatim, as produced by the old
 *  `getTargetContent` + plain string-append in `configurePodfile` before this change. */
function legacyBlock(targetName: string): string {
  return `
# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  require 'pathname'
  project_root = "#{Pod::Config.instance.installation_root}/.."
  voltra_client_root = \`node --print "require.resolve('@use-voltra/ios-client/package.json', {paths: ['#{project_root}']})" 2>/dev/null\`.strip.gsub('/package.json', '')
  voltra_widget_podspec_root = File.join(voltra_client_root, 'ios')
  podspec_dir_path = Pathname.new(voltra_widget_podspec_root).relative_path_from(Pathname.new(__dir__)).to_path

  pod 'VoltraWidget', :path => podspec_dir_path
end`
}

function countOccurrences(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1
}

describe('upsertWidgetTarget', () => {
  it('appends a marked block to a fresh Podfile, exactly once', () => {
    const result = upsertWidgetTarget(BASE_PODFILE, TARGET_NAME)

    expect(countOccurrences(result, BEGIN_MARKER)).toBe(1)
    expect(countOccurrences(result, END_MARKER)).toBe(1)
    expect(result).toContain(`target '${TARGET_NAME}' do`)
    // user content untouched
    expect(result).toContain("target 'MyApp' do")
    expect(result).toContain("target 'MyAppTests' do")
  })

  it('replaces an existing marked block in place, without duplicating it', () => {
    const withOldTarget = upsertWidgetTarget(BASE_PODFILE, TARGET_NAME)
    // Corrupt/age the inner content so we can assert it's actually replaced, not just re-appended.
    const aged = withOldTarget.replace("pod 'VoltraWidget'", "pod 'VoltraWidgetSTALE'")

    const result = upsertWidgetTarget(aged, TARGET_NAME)

    expect(result).not.toContain('VoltraWidgetSTALE')
    expect(result).toContain("pod 'VoltraWidget'")
    expect(countOccurrences(result, BEGIN_MARKER)).toBe(1)
    expect(countOccurrences(result, END_MARKER)).toBe(1)
    // surrounding user content untouched
    expect(result).toContain("target 'MyApp' do")
    expect(result).toContain("target 'MyAppTests' do")
  })

  it('replaces a legacy (v2.1.0, unmarked) block with a marked one, without duplication', () => {
    const withLegacy = `${BASE_PODFILE}\n${legacyBlock(TARGET_NAME)}`

    const result = upsertWidgetTarget(withLegacy, TARGET_NAME)

    // header comment survives (it's carried over into the marked block), but only once, and now
    // immediately preceded by the BEGIN marker rather than floating unmarked.
    expect(countOccurrences(result, '# Voltra Widget Extension Target')).toBe(1)
    expect(countOccurrences(result, BEGIN_MARKER)).toBe(1)
    expect(countOccurrences(result, END_MARKER)).toBe(1)
    expect(countOccurrences(result, `target '${TARGET_NAME}' do`)).toBe(1)
    expect(result).toContain(`${BEGIN_MARKER}\n# Voltra Widget Extension Target`)
    expect(result).toContain('DO NOT MODIFY')
    // user content untouched
    expect(result).toContain("target 'MyApp' do")
    expect(result).toContain("target 'MyAppTests' do")
  })

  it('is idempotent — applying twice equals applying once', () => {
    const once = upsertWidgetTarget(BASE_PODFILE, TARGET_NAME)
    const twice = upsertWidgetTarget(once, TARGET_NAME)

    expect(twice).toBe(once)
  })

  it('generates Ruby with the resolution-failure guard and the realpath canonicalization', () => {
    const result = upsertWidgetTarget(BASE_PODFILE, TARGET_NAME)

    expect(result).toContain(
      'raise "Voltra: could not resolve @use-voltra/ios-client from #{project_root}. Is @use-voltra/ios-client installed, and is node on PATH for pod install?" if voltra_client_root.empty?'
    )
    expect(result).toContain(
      'voltra_widget_podspec_root = File.realpath(voltra_widget_podspec_root) if File.exist?(voltra_widget_podspec_root)'
    )
  })

  it('replaces a marked block even when the target was renamed (markers are name-agnostic)', () => {
    const withOldName = upsertWidgetTarget(BASE_PODFILE, 'OldWidgetName')

    const result = upsertWidgetTarget(withOldName, 'NewWidgetName')

    expect(result).not.toContain("target 'OldWidgetName' do")
    expect(result).toContain("target 'NewWidgetName' do")
    expect(countOccurrences(result, BEGIN_MARKER)).toBe(1)
    expect(countOccurrences(result, END_MARKER)).toBe(1)
  })

  it('handles a Podfile with multiple pre-existing targets and no trailing newline at EOF', () => {
    const noTrailingNewline = BASE_PODFILE.trimEnd()

    const result = upsertWidgetTarget(noTrailingNewline, TARGET_NAME)

    expect(countOccurrences(result, BEGIN_MARKER)).toBe(1)
    expect(result).toContain("target 'MyApp' do")
    expect(result).toContain("target 'MyAppTests' do")
    expect(result).toContain(`target '${TARGET_NAME}' do`)
  })
})
