import { ConfigPlugin, withPodfile as withExpoPodfile } from '@expo/config-plugins'

/**
 * Generates the Podfile target content for the widget extension.
 */
function getTargetContent(targetName: string): string {
  return `
# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  require 'pathname'
  project_root = "#{Pod::Config.instance.installation_root}/.."
  voltra_client_root = \`node --print "require.resolve('@use-voltra/ios-client/package.json', {paths: ['#{project_root}']})" 2>/dev/null\`.strip.gsub('/package.json', '')
  voltra_widget_podspec_root = File.join(voltra_client_root, 'ios')
  podspec_dir_path = Pathname.new(voltra_widget_podspec_root).relative_path_from(Pathname.new(__dir__)).to_path

  pod 'VoltraWidget', :path => podspec_dir_path
end`
}

export interface ConfigurePodfileProps {
  targetName: string
}

/**
 * Plugin step that adds the Podfile target for the widget extension.
 */
export const configurePodfile: ConfigPlugin<ConfigurePodfileProps> = (config, { targetName }) => {
  return withExpoPodfile(config, (podfile) => {
    const targetContent = getTargetContent(targetName)

    // Check if target already exists (avoid duplicates)
    const targetMarker = "target '" + targetName + "'"
    if (podfile.modResults.contents.includes(targetMarker)) {
      return podfile
    }

    podfile.modResults.contents = podfile.modResults.contents + '\n' + targetContent
    return podfile
  })
}
