import { resolveProjectModulePath } from './resolveProjectModule'

/**
 * Hermes on Android implements `Intl.Collator`, `Intl.NumberFormat` and `Intl.DateTimeFormat`, but
 * not `Intl.PluralRules`, `Intl.RelativeTimeFormat`, `Intl.ListFormat`, `Intl.DisplayNames` or
 * `Intl.Locale` (ADR 0009 §5). JavaScriptCore on iOS has all of them, so the prelude is Android-only
 * and reaches the bundle through the `.android.js` render shim; iOS bundles stay polyfill-free.
 *
 * Order matters: each FormatJS polyfill depends on the ones before it.
 */
export const ANDROID_INTL_POLYFILL_PACKAGES = [
  '@formatjs/intl-getcanonicallocales',
  '@formatjs/intl-locale',
  '@formatjs/intl-pluralrules',
  '@formatjs/intl-listformat',
  '@formatjs/intl-displaynames',
  '@formatjs/intl-relativetimeformat',
] as const

/** Packages that ship per-locale data under `<package>/locale-data/<language>`. */
const LOCALE_DATA_PACKAGES = [
  '@formatjs/intl-pluralrules',
  '@formatjs/intl-listformat',
  '@formatjs/intl-displaynames',
  '@formatjs/intl-relativetimeformat',
] as const

export type AndroidIntlPolyfillsOptions = {
  /**
   * Languages to load locale data for, as BCP-47 tags (`"en"`, `"pl"`, `"pt-BR"`). Data is loaded
   * per language, so `pt-BR` and `pt-PT` share `pt`. List every language the widgets render in.
   */
  locales: string[]
}

export type VoltraMetroOptions = {
  /**
   * Opt in to FormatJS polyfills for the `Intl` APIs Hermes lacks, in Android widget bundles only.
   * Requires the packages in {@link ANDROID_INTL_POLYFILL_PACKAGES} to be installed in the app.
   */
  androidIntlPolyfills?: AndroidIntlPolyfillsOptions
}

/**
 * Where `withVoltra` leaves its options on the Metro config it returns, so the release bundler,
 * which loads the app's Metro config from disk, sees the same options the dev server does. A symbol
 * survives Metro's config merging (object spread) and is invisible to its unknown-key validation.
 */
export const VOLTRA_METRO_OPTIONS = Symbol.for('@use-voltra/metro/options')

export function readVoltraMetroOptions(config: unknown): VoltraMetroOptions {
  if (config && typeof config === 'object') {
    const options = (config as Record<symbol, unknown>)[VOLTRA_METRO_OPTIONS]
    if (options && typeof options === 'object') {
      return options as VoltraMetroOptions
    }
  }
  return {}
}

export function attachVoltraMetroOptions<T extends object>(config: T, options: VoltraMetroOptions): T {
  return Object.assign(config, { [VOLTRA_METRO_OPTIONS]: options })
}

/** Language subtags to load data for, lower-cased, de-duplicated, in the given order. */
export function intlPolyfillLanguages(locales: readonly string[]): string[] {
  const languages: string[] = []
  for (const locale of locales) {
    const language = locale.trim().replace(/_/g, '-').split('-')[0]?.toLowerCase()
    if (language && /^[a-z]{2,8}$/.test(language) && !languages.includes(language)) {
      languages.push(language)
    }
  }
  return languages
}

export function validateAndroidIntlPolyfillsOptions(options: unknown): AndroidIntlPolyfillsOptions | undefined {
  if (options === undefined) {
    return undefined
  }
  const locales = (options as { locales?: unknown } | null)?.locales
  if (!Array.isArray(locales) || locales.some((locale) => typeof locale !== 'string')) {
    throw new Error('[voltra] withVoltra androidIntlPolyfills.locales must be an array of BCP-47 language tags')
  }
  if (intlPolyfillLanguages(locales).length === 0) {
    throw new Error('[voltra] withVoltra androidIntlPolyfills.locales must name at least one language, e.g. ["en"]')
  }
  return { locales }
}

/**
 * Throws a clear error naming the packages to install when any polyfill package is missing, instead
 * of a Metro "unable to resolve" deep inside a generated file.
 */
export function assertAndroidIntlPolyfillsInstalled(
  projectRoot: string,
  resolve: (specifier: string, projectRoot: string) => string = resolveProjectModulePath
): void {
  const missing = ANDROID_INTL_POLYFILL_PACKAGES.filter((packageName) => {
    try {
      resolve(`${packageName}/package.json`, projectRoot)
      return false
    } catch {
      return true
    }
  })

  if (missing.length > 0) {
    throw new Error(
      `[voltra] androidIntlPolyfills is enabled, but ${missing.join(', ')} ${
        missing.length === 1 ? 'is' : 'are'
      } not installed. Add ${missing.length === 1 ? 'it' : 'them'} to the app's dependencies.`
    )
  }
}

/** Source of the Android-only prelude the `.android.js` render shim imports first. */
export function createAndroidIntlPreludeSource(options: AndroidIntlPolyfillsOptions): string {
  const languages = intlPolyfillLanguages(options.locales)
  const lines = ['// AUTO-GENERATED by @use-voltra/metro - Android Intl polyfills (ADR 0009).']
  for (const packageName of ANDROID_INTL_POLYFILL_PACKAGES) {
    lines.push(`import '${packageName}/polyfill'`)
    if ((LOCALE_DATA_PACKAGES as readonly string[]).includes(packageName)) {
      for (const language of languages) {
        lines.push(`import '${packageName}/locale-data/${language}'`)
      }
    }
  }
  return `${lines.join('\n')}\n`
}
