import fs from 'node:fs'
import path from 'node:path'

import { ConfigPlugin, withPodfile as withExpoPodfile } from '@expo/config-plugins'

import { logger } from '../utils/logger'

/**
 * Generates the Podfile target content for the widget extension.
 */
function getTargetContent(targetName: string, libraryName: string): string {
  const backtick = '`'
  return `
# Voltra Widget Extension Target
# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN
target '${targetName}' do
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  require 'json'
  require 'pathname'
  project_root = "#{Pod::Config.instance.installation_root}/.."
  podspec_name = 'VoltraWidget.podspec'
  node_modules_podspec = File.join(project_root, 'node_modules', '${libraryName}', 'ios', podspec_name)
  monorepo_podspec = File.expand_path("../ios/#{podspec_name}", project_root)

  podspec_dir_path = nil
  if File.exist?(node_modules_podspec)
    podspec_dir_path = File.dirname(node_modules_podspec)
  elsif File.exist?(monorepo_podspec)
    podspec_dir_path = File.dirname(monorepo_podspec)
  else
    voltra_module = JSON.parse(${backtick}npx expo-modules-autolinking search -p apple --json --project-root #{project_root}${backtick})
    podspec_dir_path = File.join(voltra_module['${libraryName}']['path'], 'ios')
  end

  podspec_dir_path = Pathname.new(podspec_dir_path).relative_path_from(Pathname.new(__dir__)).to_path

  pod 'VoltraWidget', :path => podspec_dir_path
end`
}

export interface ConfigurePodfileProps {
  targetName: string
}

function getLibraryName(): string {
  let dir = __dirname
  while (dir !== path.dirname(dir)) {
    const candidate = path.join(dir, 'package.json')
    if (fs.existsSync(candidate)) {
      try {
        const name = JSON.parse(fs.readFileSync(candidate, 'utf8')).name
        if (typeof name === 'string' && name.trim()) {
          return name
        }
      } catch {}
    }
    dir = path.dirname(dir)
  }
  logger.warn('Could not resolve package name. Falling back to "voltra".')
  return 'voltra'
}

/**
 * Plugin step that adds the Podfile target for the widget extension.
 */
export const configurePodfile: ConfigPlugin<ConfigurePodfileProps> = (config, { targetName }) => {
  return withExpoPodfile(config, (podfile) => {
    const libraryName = getLibraryName()
    const targetContent = getTargetContent(targetName, libraryName)

    // Check if target already exists (avoid duplicates)
    const targetMarker = "target '" + targetName + "'"
    if (podfile.modResults.contents.includes(targetMarker)) {
      return podfile
    }

    podfile.modResults.contents = podfile.modResults.contents + '\n' + targetContent
    return podfile
  })
}
