import dedent from 'dedent'

import { getDynamicLiveActivityAttributesType } from '@use-voltra/expo-plugin'

import type { IOSDynamicLiveActivityConfig } from '../../types'
import { escapeForSwiftStringLiteral } from '../files/swift-utils'

export function generateDynamicLiveActivityWidgetInstances(liveActivities: IOSDynamicLiveActivityConfig[]): string {
  return sortedDefinitions(liveActivities)
    .map((liveActivity) => `VoltraDynamicLiveActivity_${getDynamicLiveActivityAttributesType(liveActivity.id)}()`)
    .join('\n    ')
}

/** Generates the Dynamic Live Activity types shared by the app and extension targets. */
export function generateDynamicLiveActivityTypesSwift(liveActivities: IOSDynamicLiveActivityConfig[]): string {
  const definitions = sortedDefinitions(liveActivities)
  const typeDefinitions = definitions.map(generateDynamicLiveActivitySwift).map(normalizeIndent).join('\n\n')

  const header = dedent`
    //
    //  VoltraDynamicLiveActivityTypes.swift
    //
    //  Auto-generated by Voltra config plugin. Do not edit.
    //

    import ActivityKit
    import Foundation

    import VoltraRuntime

    @objc(VoltraGeneratedDynamicLiveActivityRegistration)
    public final class VoltraGeneratedDynamicLiveActivityRegistration: NSObject {
      @objc public static func registerDefinitions() {
${definitions
  .map(
    (liveActivity) =>
      `        VoltraDynamicLiveActivityRegistry.shared.register(${getDynamicLiveActivityAttributesType(
        liveActivity.id
      )}.self)`
  )
  .join('\n')}
      }
    }

  `
  return [header.trim(), typeDefinitions.trim()].filter(Boolean).join('\n\n')
}

/** Generates extension-only ActivityConfiguration declarations for Dynamic Live Activities. */
export function generateDynamicLiveActivitiesSwift(liveActivities: IOSDynamicLiveActivityConfig[]): string {
  const configurations = sortedDefinitions(liveActivities)
    .map((liveActivity) => {
      const attributesType = getDynamicLiveActivityAttributesType(liveActivity.id)
      const definitionId = escapeForSwiftStringLiteral(liveActivity.id)
      return dedent`
        public struct VoltraDynamicLiveActivity_${attributesType}: Widget {
          public init() {}

          public var body: some WidgetConfiguration {
            if #available(iOS 18.0, *) {
              return adaptiveConfig()
            } else {
              return defaultConfig()
            }
          }

          @available(iOS 18.0, *)
          private func adaptiveConfig() -> some WidgetConfiguration {
            ActivityConfiguration(for: ${attributesType}.self) { context in
              VoltraDynamicLiveActivityRenderer.lockScreen(definitionId: "${definitionId}", context: context)
            } dynamicIsland: { context in
              VoltraDynamicLiveActivityRenderer.dynamicIsland(definitionId: "${definitionId}", context: context)
            }
            .supplementalActivityFamilies([.small, .medium])
          }

          private func defaultConfig() -> some WidgetConfiguration {
            ActivityConfiguration(for: ${attributesType}.self) { context in
              VoltraDynamicLiveActivityRenderer.lockScreen(definitionId: "${definitionId}", context: context)
            } dynamicIsland: { context in
              VoltraDynamicLiveActivityRenderer.dynamicIsland(definitionId: "${definitionId}", context: context)
            }
          }
        }
      `
    })
    .map(normalizeIndent)
    .join('\n\n')

  const header = dedent`
    //
    //  VoltraDynamicLiveActivities.swift
    //
    //  Auto-generated by Voltra config plugin. Do not edit.
    //

    import ActivityKit
    import SwiftUI
    import WidgetKit
    import VoltraRuntime

  `
  return [header.trim(), configurations.trim()].filter(Boolean).join('\n\n')
}

function generateDynamicLiveActivitySwift(liveActivity: IOSDynamicLiveActivityConfig): string {
  const attributesType = getDynamicLiveActivityAttributesType(liveActivity.id)
  const definitionId = escapeForSwiftStringLiteral(liveActivity.id)

  return dedent`
    public struct ${attributesType}: ActivityAttributes {
      public typealias ContentState = VoltraDynamicLiveActivityContentState

      public let name: String
      public let deepLinkUrl: String?

      public init(name: String, deepLinkUrl: String?) {
        self.name = name
        self.deepLinkUrl = deepLinkUrl
      }
    }

    extension ${attributesType}: VoltraDynamicLiveActivityDefinition {
      public static let definitionId = "${definitionId}"
    }

  `
}

function sortedDefinitions(liveActivities: IOSDynamicLiveActivityConfig[]): IOSDynamicLiveActivityConfig[] {
  return [...liveActivities].sort((left, right) => left.id.localeCompare(right.id))
}

function normalizeIndent(source: string): string {
  const lines = source.trim().split('\n')
  const indent = Math.min(...lines.filter(Boolean).map((line) => line.match(/^\s*/)?.[0].length ?? 0))
  return lines.map((line) => line.slice(indent)).join('\n')
}
