import path from 'node:path'
import { createRequire } from 'node:module'

import { readTextFile, writeTextFile } from '../../fs/readWrite'
import { toRelativePath } from '../../fs/path'
import { VoltraCliError } from '../../reporting/summary'
import { resolveIOSWidgetTargetName } from './targetName'
import { VOLTRA_MIN_IOS_DEPLOYMENT_TARGET, isIOSDeploymentTargetAtLeast } from './deploymentTarget'

import type { IOSProjectDiscovery } from '../../discovery/ios'
import type { NormalizedVoltraIOSConfig } from '../../config/types'
import type { ReportedChange } from '../../reporting/summary'

const VOLTRA_MANAGED_BLOCK_START = '# >>> VOLTRA MANAGED BLOCK: widget extension target'
const VOLTRA_MANAGED_BLOCK_END = '# <<< VOLTRA MANAGED BLOCK: widget extension target'
const LEGACY_BLOCK_HEADER = '# Voltra Widget Extension Target'
const LEGACY_BLOCK_NOTICE = '# DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED BY THE VOLTRA PLUGIN'

export interface EnsurePodfileBlockOptions {
  projectRoot: string
  ios: NormalizedVoltraIOSConfig
  discovery: IOSProjectDiscovery
}

export interface EnsurePodfileBlockResult {
  change?: ReportedChange
  targetName: string
  warnings?: string[]
}

export class IOSPodfileMutationError extends VoltraCliError {
  constructor(message: string) {
    super(message, 'VOLTRA_IOS_PODFILE_FAILED')
    this.name = 'IOSPodfileMutationError'
  }
}

export async function ensurePodfileBlock(options: EnsurePodfileBlockOptions): Promise<EnsurePodfileBlockResult> {
  const { projectRoot, ios, discovery } = options
  const targetName = resolveIOSWidgetTargetName(ios, discovery)
  const currentContent = await readPodfile(discovery.podfilePath)
  const nextBlock = buildManagedPodfileBlock(targetName)
  const platformResult = await ensurePodfileDeploymentTarget(currentContent, projectRoot)
  const nextContent = reconcilePodfile(platformResult.content, nextBlock, targetName)

  if (currentContent === nextContent) {
    return { targetName, warnings: platformResult.warnings }
  }

  await writeTextFile(discovery.podfilePath, nextContent)

  return {
    change: {
      kind: 'updated',
      path: toRelativePath(projectRoot, discovery.podfilePath),
    },
    targetName,
    warnings: platformResult.warnings,
  }
}

interface EnsurePodfileDeploymentTargetResult {
  content: string
  warnings?: string[]
}

async function ensurePodfileDeploymentTarget(
  content: string,
  projectRoot: string
): Promise<EnsurePodfileDeploymentTargetResult> {
  const lines = content.split('\n')
  const platformLineIndex = lines.findIndex((line) => /^\s*platform\s+:ios\s*,/.test(line))

  if (platformLineIndex === -1) {
    return {
      content,
      warnings: [
        `Could not find an iOS platform declaration in the Podfile. Ensure it resolves to iOS ${VOLTRA_MIN_IOS_DEPLOYMENT_TARGET} or newer.`,
      ],
    }
  }

  const line = lines[platformLineIndex]
  const match = line.match(/^(\s*platform\s+:ios\s*,\s*)(.*?)(\s*(?:#.*)?)$/)

  if (!match) {
    return {
      content,
      warnings: [getUnknownPodfilePlatformWarning()],
    }
  }

  const [, prefix, rawValue, suffix] = match
  const platformValue = rawValue.trim()
  const nextValue = await resolveNextPodfilePlatformValue(platformValue, projectRoot)

  if (nextValue === undefined) {
    return {
      content,
      warnings: [getUnknownPodfilePlatformWarning()],
    }
  }

  if (nextValue === platformValue) {
    return { content }
  }

  lines[platformLineIndex] = `${prefix}${nextValue}${suffix}`
  return { content: lines.join('\n') }
}

async function resolveNextPodfilePlatformValue(
  platformValue: string,
  projectRoot: string
): Promise<string | undefined> {
  const literalVersion = parseRubyStringLiteral(platformValue)

  if (literalVersion) {
    return isIOSDeploymentTargetAtLeast(literalVersion, VOLTRA_MIN_IOS_DEPLOYMENT_TARGET)
      ? platformValue
      : `'${VOLTRA_MIN_IOS_DEPLOYMENT_TARGET}'`
  }

  if (platformValue === 'min_ios_version_supported') {
    const reactNativeMinVersion = await resolveReactNativeMinIOSVersion(projectRoot)

    if (
      reactNativeMinVersion &&
      isIOSDeploymentTargetAtLeast(reactNativeMinVersion, VOLTRA_MIN_IOS_DEPLOYMENT_TARGET)
    ) {
      return platformValue
    }

    return `'${VOLTRA_MIN_IOS_DEPLOYMENT_TARGET}'`
  }

  return undefined
}

function parseRubyStringLiteral(value: string): string | undefined {
  const match = value.match(/^(['"])(\d+(?:\.\d+){0,2})\1$/)
  return match?.[2]
}

async function resolveReactNativeMinIOSVersion(projectRoot: string): Promise<string | undefined> {
  try {
    const requireFromProject = createRequire(path.join(projectRoot, 'package.json'))
    const reactNativePackagePath = requireFromProject.resolve('react-native/package.json')
    const helpersPath = path.join(path.dirname(reactNativePackagePath), 'scripts', 'cocoapods', 'helpers.rb')
    const helpersContent = await readTextFile(helpersPath)
    return helpersContent.match(/def self\.min_ios_version_supported[\s\S]*?return ['"]([^'"]+)['"]/)?.[1]
  } catch {
    return undefined
  }
}

function getUnknownPodfilePlatformWarning(): string {
  return `Could not verify the Podfile iOS platform declaration. Ensure it resolves to iOS ${VOLTRA_MIN_IOS_DEPLOYMENT_TARGET} or newer.`
}

function buildManagedPodfileBlock(targetName: string): string {
  const escapedTargetName = escapeRubySingleQuotedString(targetName)

  return [
    VOLTRA_MANAGED_BLOCK_START,
    '# Voltra widget extension target managed by voltra apply.',
    `target '${escapedTargetName}' do`,
    "  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if defined?(podfile_properties) && podfile_properties['ios.useFrameworks']",
    "  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']",
    '',
    "  require 'pathname'",
    '  project_root = "#{Pod::Config.instance.installation_root}/.."',
    "  abort('[voltra] Error: @use-voltra/ios-client must be installed in the app project before running pod install.') unless system(\"node --print \\\"require.resolve('@use-voltra/ios-client/package.json', {paths: ['#{project_root}']})\\\" >/dev/null 2>&1\")",
    "  voltra_client_root = `node --print \"require.resolve('@use-voltra/ios-client/package.json', {paths: ['#{project_root}']})\" 2>/dev/null`.strip.gsub('/package.json', '')",
    "  voltra_widget_podspec_root = File.join(voltra_client_root, 'ios')",
    '  podspec_dir_path = Pathname.new(voltra_widget_podspec_root).relative_path_from(Pathname.new(__dir__)).to_path',
    '',
    "  pod 'VoltraWidget', :path => podspec_dir_path",
    'end',
    VOLTRA_MANAGED_BLOCK_END,
  ].join('\n')
}

function reconcilePodfile(currentContent: string, nextBlock: string, targetName: string): string {
  const normalizedContent = stripTrailingWhitespace(currentContent)
  const managedBlockPattern = createManagedBlockPattern()
  const legacyBlockPattern = createLegacyBlockPattern()

  if (managedBlockPattern.test(normalizedContent)) {
    return ensureTrailingNewline(normalizedContent.replace(managedBlockPattern, nextBlock))
  }

  if (legacyBlockPattern.test(normalizedContent)) {
    return ensureTrailingNewline(normalizedContent.replace(legacyBlockPattern, nextBlock))
  }

  if (hasUnmanagedTargetBlock(normalizedContent, targetName)) {
    throw new IOSPodfileMutationError(
      `Podfile already contains an unmanaged target '${targetName}'. Remove it or choose a different ios.targetName before running voltra apply.`
    )
  }

  const separator = normalizedContent.length === 0 ? '' : '\n\n'
  return ensureTrailingNewline(`${normalizedContent}${separator}${nextBlock}`)
}

function createManagedBlockPattern(): RegExp {
  return new RegExp(
    `${escapeRegExp(VOLTRA_MANAGED_BLOCK_START)}[\\s\\S]*?${escapeRegExp(VOLTRA_MANAGED_BLOCK_END)}`,
    'm'
  )
}

function createLegacyBlockPattern(): RegExp {
  return new RegExp(
    `${escapeRegExp(LEGACY_BLOCK_HEADER)}\\n${escapeRegExp(LEGACY_BLOCK_NOTICE)}\\ntarget '[^']+' do[\\s\\S]*?\\nend`,
    'm'
  )
}

async function readPodfile(podfilePath: string): Promise<string> {
  try {
    return await readTextFile(podfilePath)
  } catch (error: unknown) {
    throw new IOSPodfileMutationError(`Failed to read Podfile at ${podfilePath}: ${getErrorMessage(error)}`)
  }
}

function stripTrailingWhitespace(value: string): string {
  return value.replace(/\s+$/, '')
}

function ensureTrailingNewline(value: string): string {
  return `${value}\n`
}

function escapeRubySingleQuotedString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function hasUnmanagedTargetBlock(content: string, targetName: string): boolean {
  const targetPattern = new RegExp(
    `(^|\\n)target '${escapeRegExp(escapeRubySingleQuotedString(targetName))}' do(\\n|$)`,
    'm'
  )
  return targetPattern.test(content)
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}
