//
//  ShortNames.swift
//
//  AUTO-GENERATED from data/components.json
//  DO NOT EDIT MANUALLY - Changes will be overwritten
//  Schema version: 1.0.0

import Foundation

/// Unified short name mappings for props and style properties
/// Used to expand compressed payload keys back to their full names
public enum ShortNames {
  /// Mapping from short names to full names
  private static let shortToName: [String: String] = [
    "ap": "absolutePosition",
    "arm": "accentedRenderingMode",
    "ai": "alignItems",
    "al": "alignment",
    "as": "alignSelf",
    "a": "alpha",
    "ar": "aspectRatio",
    "an": "assetName",
    "bkg": "background",
    "bg": "backgroundColor",
    "bgs": "backgroundStyle",
    "b64": "base64",
    "bd": "border",
    "bc": "borderColor",
    "br": "borderRadius",
    "bw": "borderWidth",
    "b": "bottom",
    "bs": "buttonStyle",
    "csa": "chartScrollableAxes",
    "chk": "checked",
    "chc": "checkedColor",
    "clip": "clipped",
    "c": "color",
    "cf": "colorFilter",
    "cls": "colors",
    "cols": "columns",
    "ca": "contentAlignment",
    "cc": "contentColor",
    "cdesc": "contentDescription",
    "csc": "contentScale",
    "cr": "cornerRadius",
    "cd": "countDown",
    "cvl": "currentValueLabel",
    "dlu": "deepLinkUrl",
    "dv": "defaultValue",
    "dest": "destination",
    "dir": "direction",
    "dth": "dither",
    "dur": "durationMs",
    "en": "enabled",
    "end": "endAtMs",
    "ep": "endPoint",
    "flb": "fallback",
    "fmh": "fillMaxHeight",
    "fmw": "fillMaxWidth",
    "fsh": "fixedSizeHorizontal",
    "fsv": "fixedSizeVertical",
    "fl": "flex",
    "fb": "flexBasis",
    "fdir": "flexDirection",
    "fg": "flexGrow",
    "fgw": "flexGrowWidth",
    "fk": "flexShrink",
    "fnt": "font",
    "ff": "fontFamily",
    "fs": "fontSize",
    "fvar": "fontVariant",
    "fw": "fontWeight",
    "fgs": "foregroundStyle",
    "fss": "foregroundStyleScale",
    "f": "frame",
    "g": "gap",
    "gs": "gaugeStyle",
    "ge": "glassEffect",
    "h": "height",
    "halig": "horizontalAlignment",
    "hp": "horizontalPadding",
    "ic": "icon",
    "icc": "iconColor",
    "id": "id",
    "it": "italic",
    "jc": "justifyContent",
    "kern": "kerning",
    "lbl": "label",
    "ly": "layout",
    "lp": "layoutPriority",
    "l": "left",
    "lgv": "legendVisibility",
    "ls": "letterSpacing",
    "lh": "lineHeight",
    "ll": "lineLimit",
    "lsp": "lineSpacing",
    "lw": "lineWidth",
    "m": "margin",
    "mb": "marginBottom",
    "mh": "marginHorizontal",
    "ml": "marginLeft",
    "mr": "marginRight",
    "mt": "marginTop",
    "mv": "marginVertical",
    "mrk": "marks",
    "me": "maskElement",
    "maxh": "maxHeight",
    "max": "maximumValue",
    "maxl": "maximumValueLabel",
    "mxl": "maxLines",
    "maxw": "maxWidth",
    "minh": "minHeight",
    "min": "minimumValue",
    "minvl": "minimumValueLabel",
    "minl": "minLength",
    "minw": "minWidth",
    "md": "monospacedDigit",
    "mta": "multilineTextAlignment",
    "n": "name",
    "nol": "numberOfLines",
    "off": "offset",
    "ox": "offsetX",
    "oy": "offsetY",
    "op": "opacity",
    "ov": "overflow",
    "pad": "padding",
    "pb": "paddingBottom",
    "ph": "paddingHorizontal",
    "pl": "paddingLeft",
    "pr": "paddingRight",
    "pt": "paddingTop",
    "pv": "paddingVertical",
    "pos": "position",
    "prg": "progress",
    "pc": "progressColor",
    "rm": "resizeMode",
    "r": "right",
    "re": "rotationEffect",
    "sc": "scale",
    "sce": "scaleEffect",
    "sh": "shadow",
    "shc": "shadowColor",
    "sho": "shadowOffset",
    "shop": "shadowOpacity",
    "shr": "shadowRadius",
    "shrs": "showHours",
    "sz": "size",
    "smc": "smallCaps",
    "src": "source",
    "sp": "spacing",
    "start": "startAtMs",
    "sic": "startIcon",
    "stp": "startPoint",
    "sts": "stops",
    "st": "strikethrough",
    "s": "style",
    "si": "systemImage",
    "txt": "text",
    "ta": "textAlign",
    "txc": "textColor",
    "tdl": "textDecorationLine",
    "ts": "textStyle",
    "tt": "textTemplates",
    "th": "thumb",
    "thc": "thumbCheckedColor",
    "thu": "thumbUncheckedColor",
    "tnt": "tint",
    "tc": "tintColor",
    "ttl": "title",
    "t": "top",
    "trkc": "trackCheckedColor",
    "trc": "trackColor",
    "trku": "trackUncheckedColor",
    "tf": "transform",
    "typ": "type",
    "uchc": "uncheckedColor",
    "ul": "underline",
    "v": "value",
    "valig": "verticalAlignment",
    "wt": "weight",
    "w": "width",
    "xgs": "xAxisGridStyle",
    "xav": "xAxisVisibility",
    "ygs": "yAxisGridStyle",
    "yav": "yAxisVisibility",
    "zi": "zIndex",
  ]

  /// Expand a short name to its full form
  /// - Parameter short: The short name (e.g., "bg", "al", "sp")
  /// - Returns: The full name (e.g., "backgroundColor", "alignment", "spacing"), or the input if no mapping exists
  public static func expand(_ short: String) -> String {
    shortToName[short] ?? short
  }
}
