import Foundation
import SwiftUI
import WidgetKit

/// Shared rendering helpers for AppIntentConfiguration widgets generated by the Voltra config plugin.
/// Generated widget code calls into these so the boilerplate stays minimal.
@available(iOS 17.0, *)
public enum VoltraReactiveRenderer {
  /// Deserialises the resolved JSON payload, extracts the family-specific element,
  /// and parses it into a VoltraNode ready for the Swift interpreter.
  public static func extractNode(from resolvedJSON: String, family: WidgetFamily) -> VoltraNode {
    guard let data = resolvedJSON.data(using: .utf8),
          let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let familyContent = root[familyKey(family)] ?? root["systemSmall"],
          var reconstructed = familyContent as? [String: Any]
    else { return .empty }

    // Mirror VoltraHomeWidget.reconstructWithSharedData: copy the shared stylesheet ("s")
    // and shared elements ("e") into the family-specific object so VoltraNode.parse can
    // resolve style index references and element deduplication.
    if let stylesheet = root["s"] { reconstructed["s"] = stylesheet }
    if let elements = root["e"] { reconstructed["e"] = elements }

    guard let familyData = try? JSONSerialization.data(withJSONObject: reconstructed),
          let familyStr = String(data: familyData, encoding: .utf8),
          let jsonValue = try? JSONValue.parse(from: familyStr)
    else { return .empty }

    return VoltraNode.parse(from: jsonValue)
  }

  public static func familyKey(_ family: WidgetFamily) -> String {
    switch family {
    case .systemSmall: return "systemSmall"
    case .systemMedium: return "systemMedium"
    case .systemLarge: return "systemLarge"
    default: return "systemSmall"
    }
  }

  public static func voltraRenderingMode(_ mode: WidgetRenderingMode) -> VoltraWidgetRenderingMode {
    switch mode {
    case .accented: return .accented
    case .vibrant: return .vibrant
    default: return .fullColor
    }
  }
}

/// Applies `.containerBackground(.clear, for: .widget)`.
/// Used by all generated AppIntentConfiguration widget views (always iOS 17+).
@available(iOS 17.0, *)
public struct VoltraReactiveContainerBackground: ViewModifier {
  public init() {}

  public func body(content: Content) -> some View {
    content.containerBackground(.clear, for: .widget)
  }
}
