import dedent from 'dedent'
import * as fs from 'fs'
import * as path from 'path'

import { DEFAULT_WIDGET_FAMILIES, WIDGET_FAMILY_MAP } from '../../constants'
import type { WidgetConfig } from '../../types'
import { logger } from '../../utils/logger'
import { prerenderWidgetState } from '../../utils/prerender'

export interface GenerateSwiftFilesOptions {
  targetPath: string
  projectRoot: string
  widgets?: WidgetConfig[]
}

// ============================================================================
// Main Function
// ============================================================================

/**
 * Generates all Swift files for the widget extension.
 *
 * This creates:
 * - VoltraWidgetInitialStates.swift (pre-rendered widget states)
 * - VoltraWidgetBundle.swift (widget bundle definition)
 */
export async function generateSwiftFiles(options: GenerateSwiftFilesOptions): Promise<void> {
  const { targetPath, projectRoot, widgets } = options

  // Dynamic import for ESM module compatibility
  // voltra/server is an ESM module, but the plugin is compiled to CommonJS
  const { renderWidgetToString } = await import('voltra/server')

  // Prerender widget initial states if any widgets have initialStatePath configured
  const prerenderedStates = await prerenderWidgetState(widgets || [], projectRoot, renderWidgetToString)

  // Generate the initial states Swift file
  const initialStatesContent = generateInitialStatesSwift(prerenderedStates)
  const initialStatesPath = path.join(targetPath, 'VoltraWidgetInitialStates.swift')
  fs.writeFileSync(initialStatesPath, initialStatesContent)

  logger.info(`Generated VoltraWidgetInitialStates.swift with ${prerenderedStates.size} pre-rendered widget states`)

  // Generate the widget bundle Swift file
  const widgetBundleContent =
    widgets && widgets.length > 0 ? generateWidgetBundleSwift(widgets) : generateDefaultWidgetBundleSwift()

  const widgetBundlePath = path.join(targetPath, 'VoltraWidgetBundle.swift')
  fs.writeFileSync(widgetBundlePath, widgetBundleContent)

  logger.info(`Generated VoltraWidgetBundle.swift with ${widgets?.length ?? 0} home screen widgets`)
}

// ============================================================================
// Widget Bundle
// ============================================================================

/**
 * Generates Swift code for a single widget struct
 */
function generateWidgetStruct(widget: WidgetConfig): string {
  const families = widget.supportedFamilies ?? DEFAULT_WIDGET_FAMILIES
  const familiesSwift = families.map((f) => WIDGET_FAMILY_MAP[f]).join(', ')

  // Sanitize the widget id for use as a Swift identifier
  const structName = `VoltraWidget_${widget.id}`

  return dedent`
    public struct ${structName}: Widget {
      private let widgetId = "${widget.id}"

      public init() {}

      public var body: some WidgetConfiguration {
        StaticConfiguration(
          kind: "Voltra_Widget_${widget.id}",
          provider: VoltraHomeWidgetProvider(
            widgetId: widgetId,
            initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
          )
        ) { entry in
          VoltraHomeWidgetView(entry: entry)
        }
        .configurationDisplayName("${widget.displayName}")
        .description("${widget.description}")
        .supportedFamilies([${familiesSwift}])
        .contentMarginsDisabled()
      }
    }
  `
}

/**
 * Generates the VoltraWidgetBundle.swift file content with configured widgets
 */
function generateWidgetBundleSwift(widgets: WidgetConfig[]): string {
  // Generate widget structs
  const widgetStructs = widgets.map(generateWidgetStruct).join('\n\n')

  // Generate widget bundle body entries
  const widgetInstances = widgets.map((w) => `VoltraWidget_${w.id}()`).join('\n    ')

  return dedent`
    //
    //  VoltraWidgetBundle.swift
    //
    //  Auto-generated by Voltra config plugin.
    //  This file defines which Voltra widgets are available in your app.
    //

    import SwiftUI
    import WidgetKit
    import VoltraWidget

    @main
    struct VoltraWidgetBundle: WidgetBundle {
      var body: some Widget {
        // Live Activity (with Watch/CarPlay support)
        VoltraWidget()

        // Home Screen Widgets
        ${widgetInstances}
      }
    }

    // MARK: - Home Screen Widget Definitions

    ${widgetStructs}
  `
}

/**
 * Generates the VoltraWidgetBundle.swift file content when no widgets are configured
 * (only Live Activities)
 */
function generateDefaultWidgetBundleSwift(): string {
  return dedent`
    //
    //  VoltraWidgetBundle.swift
    //
    //  This file defines which Voltra widgets are available in your app.
    //  You can customize which widgets to include by adding or removing them below.
    //

    import SwiftUI
    import WidgetKit
    import VoltraWidget  // Import Voltra widgets

    @main
    struct VoltraWidgetBundle: WidgetBundle {
      var body: some Widget {
        // Live Activity (with Watch/CarPlay support)
        VoltraWidget()
      }
    }
  `
}

// ============================================================================
// Initial States
// ============================================================================

/**
 * Generates Swift code that bundles pre-rendered widget initial states.
 */
function generateInitialStatesSwift(prerenderedStates: Map<string, string>): string {
  if (prerenderedStates.size === 0) {
    return generateEmptyInitialStatesSwift()
  }

  // Generate the bundled states dictionary
  const stateEntries = Array.from(prerenderedStates.entries())
    .map(([widgetId, json]) => {
      const delimiter = getSwiftRawStringDelimiter(json)
      return `"${widgetId}": ${delimiter}"${json}"${delimiter}`
    })
    .join(',\n    ')

  return dedent`
    //
    //  VoltraWidgetInitialStates.swift
    //
    //  Auto-generated by Voltra config plugin.
    //  Contains pre-rendered initial states for home screen widgets.
    //

    import Foundation

    public enum VoltraWidgetInitialStates {
      private static let bundledStates: [String: String] = [
        ${stateEntries}
      ]

      /// Get the bundled initial state JSON for a widget.
      /// Returns nil if no initial state was configured for the widget.
      public static func getInitialState(for widgetId: String) -> Data? {
        guard let jsonString = bundledStates[widgetId] else { return nil }
        return jsonString.data(using: .utf8)
      }
    }
  `
}

/**
 * Generates empty Swift code when no widgets have initial states configured.
 */
function generateEmptyInitialStatesSwift(): string {
  return dedent`
    //
    //  VoltraWidgetInitialStates.swift
    //
    //  Auto-generated by Voltra config plugin.
    //  No widget initial states configured.
    //

    import Foundation

    public enum VoltraWidgetInitialStates {
      /// Get the bundled initial state JSON for a widget.
      /// Always returns nil since no initial states are configured.
      public static func getInitialState(for widgetId: String) -> Data? {
        return nil
      }
    }
  `
}

/**
 * Determines the appropriate Swift raw string delimiter for a given string.
 * Counts the maximum consecutive '#' characters after a '"' in the content
 * and returns a delimiter with one more '#' than that maximum.
 *
 * For example:
 * - Content has no '"#' → returns '#'
 * - Content has '"#' (1 hash) → returns '##'
 * - Content has '"##' (2 hashes) → returns '###'
 */
function getSwiftRawStringDelimiter(str: string): string {
  // Find all sequences of '#' that follow a '"'
  const matches = str.match(/"#+/g)

  if (!matches) {
    return '#'
  }

  // Find the maximum number of consecutive '#' after a '"'
  const maxHashes = Math.max(...matches.map((m) => m.length - 1)) // -1 to exclude the '"'
  return '#'.repeat(maxHashes + 1)
}
