import { ConfigPlugin, withAppBuildGradle } from '@expo/config-plugins'

import { logger } from '@use-voltra/expo-plugin'

import type { AndroidWidgetConfig } from '../types'
import { detectClientRenderedWidgets } from './clientRendered'

const MARKER = '// @voltra-widget-bundling'

// Release-only Gradle wiring that bakes each Dynamic Widget's production JS bundle into the
// app's assets — the Android analog of iOS's release "Bundle Voltra client widgets" build phase.
// Debug keeps fetching from Metro (and hot-reloading); only release variants depend on the task,
// and the generated dir is empty otherwise. Re-bakes every build (it can't enumerate widget-source
// inputs). The bundle lands at assets/voltra/voltra-widget-<id>.bundle, which the runtime's release
// loader reads from Bundle assets.
const GRADLE_SNIPPET = `
${MARKER} — generated by @use-voltra/android-client; do not edit
def voltraProjectRoot = file("\${rootDir}/..")
def voltraWidgetAssetsDir = file("\${buildDir}/generated/voltra/assets")
android.sourceSets.getByName("main").assets.srcDir(voltraWidgetAssetsDir)

def voltraBundleWidgets = tasks.register("voltraBundleWidgets", Exec) {
    description = "Bake Dynamic Widget Voltra bundles into assets (release)."
    workingDir voltraProjectRoot
    environment "VOLTRA_PROJECT_ROOT", voltraProjectRoot.absolutePath
    environment "VOLTRA_OUT_DIR", new File(voltraWidgetAssetsDir, "voltra").absolutePath
    environment "VOLTRA_BUNDLER_RESOLVER", "const m=require('module'),p=require('path');process.stdout.write(m.createRequire(p.join(process.argv[1],'package.json')).resolve('@use-voltra/metro/bundle-widgets'))"
    commandLine "bash", "-c", 'BUNDLER="$(node -e "$VOLTRA_BUNDLER_RESOLVER" "$VOLTRA_PROJECT_ROOT")"; if [ -z "$BUNDLER" ]; then echo "error: Voltra could not resolve @use-voltra/metro/bundle-widgets from $VOLTRA_PROJECT_ROOT — install @use-voltra/metro so release widgets can be baked." >&2; exit 1; fi; node "$BUNDLER" --platform android --out-dir "$VOLTRA_OUT_DIR" --project-root "$VOLTRA_PROJECT_ROOT"'
    outputs.upToDateWhen { false }
}

android.applicationVariants.all { variant ->
    if (variant.buildType.name == "release") {
        tasks.named("merge\${variant.name.capitalize()}Assets").configure { dependsOn voltraBundleWidgets }
    }
}
`

/**
 * Appends the release widget-bundling Gradle wiring to `app/build.gradle`, idempotently, and only
 * when at least one Dynamic Widget is present (server-rendered apps need no JS bundle baked).
 */
export const withWidgetBundleGradle: ConfigPlugin<{ widgets: AndroidWidgetConfig[] }> = (config, { widgets }) => {
  return withAppBuildGradle(config, (cfg) => {
    const hasClientRenderedWidgets = detectClientRenderedWidgets(widgets, cfg.modRequest.projectRoot).some(
      (widget) => widget.clientRendered
    )
    if (!hasClientRenderedWidgets) {
      return cfg
    }

    if (cfg.modResults.language !== 'groovy') {
      logger.warn('Voltra: app/build.gradle is not Groovy — skipping Dynamic Widget release bundling wiring.')
      return cfg
    }

    cfg.modResults.contents = addWidgetBundleGradle(cfg.modResults.contents)
    return cfg
  })
}

/** Append the widget-bundling snippet to build.gradle contents, idempotently (returns unchanged
 *  contents if already present). */
export function addWidgetBundleGradle(contents: string): string {
  if (contents.includes(MARKER)) {
    return contents
  }
  return `${contents.trimEnd()}\n${GRADLE_SNIPPET}\n`
}

export const __test__ = { MARKER, addWidgetBundleGradle }
