import { ConfigPlugin, withAppBuildGradle } from '@expo/config-plugins'

import { logger } from '@use-voltra/expo-plugin'

import type { AndroidWidgetConfig } from '../types'
import { detectClientRenderedWidgets } from './clientRendered'

const MARKER = '// @voltra-widget-bundling'

// Release-only Gradle wiring that bakes each client-rendered widget's production JS bundle into the
// app's assets — the Android analog of iOS's release "Bundle Voltra client widgets" build phase.
// Debug keeps fetching from Metro (and hot-reloading); only release variants depend on the task,
// and the generated dir is empty otherwise. Re-bakes every build (it can't enumerate widget-source
// inputs). The bundle lands at assets/voltra/voltra-widget-<id>.bundle, which the runtime's release
// loader reads from Bundle assets.
const GRADLE_SNIPPET = `
${MARKER} — generated by @use-voltra/android-client; do not edit
def voltraProjectRoot = file("\${rootDir}/..")
def voltraWidgetAssetsDir = file("\${buildDir}/generated/voltra/assets")
android.sourceSets.getByName("main").assets.srcDir(voltraWidgetAssetsDir)

def voltraBundleWidgets = tasks.register("voltraBundleWidgets", Exec) {
    description = "Bake client-rendered Voltra widget bundles into assets (release)."
    workingDir voltraProjectRoot
    commandLine "node", "metro/bundleWidgets.js", "--platform", "android", "--out-dir", new File(voltraWidgetAssetsDir, "voltra").absolutePath, "--project-root", voltraProjectRoot.absolutePath
    outputs.upToDateWhen { false }
}

android.applicationVariants.all { variant ->
    if (variant.buildType.name == "release") {
        tasks.named("merge\${variant.name.capitalize()}Assets").configure { dependsOn voltraBundleWidgets }
    }
}
`

/**
 * Appends the release widget-bundling Gradle wiring to `app/build.gradle`, idempotently, and only
 * when at least one widget is client-rendered (server-rendered apps need no JS bundle baked).
 */
export const withWidgetBundleGradle: ConfigPlugin<{ widgets: AndroidWidgetConfig[] }> = (config, { widgets }) => {
  return withAppBuildGradle(config, (cfg) => {
    const hasClientRenderedWidgets = detectClientRenderedWidgets(widgets, cfg.modRequest.projectRoot).some(
      (widget) => widget.clientRendered
    )
    if (!hasClientRenderedWidgets) {
      return cfg
    }

    if (cfg.modResults.language !== 'groovy') {
      logger.warn('Voltra: app/build.gradle is not Groovy — skipping client widget release bundling wiring.')
      return cfg
    }

    if (cfg.modResults.contents.includes(MARKER)) {
      return cfg
    }

    cfg.modResults.contents = `${cfg.modResults.contents.trimEnd()}\n${GRADLE_SNIPPET}\n`
    return cfg
  })
}
